name: OtakuWrdd
description: "Anime and Manga Tracker."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_storage: ^12.4.2
  connectivity_plus: ^6.1.2
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.2.1
  iconsax: ^0.0.8
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  google_sign_in: ^6.2.2
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image_cropper: ^9.0.0
  html: ^0.15.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_gen: ^5.3.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/otakuwrdd.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/splashscreen.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#000000"
    image: assets/images/splashscreen.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  web_image_mode: fill

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/dummy/
    - assets/images/splashscreen.png
